// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_darkLightVR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.darkLightVR_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.darkLightVR_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.darkLightVR_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.darkLightVR_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.darkLightVR_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.darkLightVR_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.darkLightVR_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.darkLightVR_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean VoiceInput
        {
            get
            {
                return SteamVR_Actions.darkLightVR_VoiceInput;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectionRay
        {
            get
            {
                return SteamVR_Actions.darkLightVR_SelectionRay;
            }
        }
        
        public virtual SteamVR_Action_Boolean CancelSelection
        {
            get
            {
                return SteamVR_Actions.darkLightVR_CancelSelection;
            }
        }
        
        public virtual SteamVR_Action_Boolean ExtraMenu
        {
            get
            {
                return SteamVR_Actions.darkLightVR_ExtraMenu;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.darkLightVR_Haptic;
            }
        }
    }
}
